// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    save: function(name, callback) {
      var user;
      user = {
        id: "2222",
        name: name
      };
      return callback(user);
    },
    get: function(id, callback) {
      var user;
      user = {
        name: "debesson",
        id: id
      };
      return callback(user);
    }
  };

}).call(this);
