// Generated by CoffeeScript 1.10.0
(function() {
  var http, users;

  http = require('http');

  users = require('./users.js');

  http.createServer(function(req, res) {
    var path;
    path = req.url.split("/").splice(1, 2);
    if (path[0] === 'get') {
      return users.get(path[1], function(user) {
        var response;
        response = {
          info: "here's your user!",
          user: user
        };
        res.writeHead(200, {
          'Content-Type': 'application/json'
        });
        return res.end(JSON.stringify(response));
      });
    } else if (path[0] === 'save') {
      return users.save(path[1], function(user) {
        var response;
        response = {
          info: "user saved!",
          user: user
        };
        res.writeHead(200, {
          'Content-Type': 'application/json'
        });
        return res.end(JSON.stringify(response));
      });
    } else {
      res.writeHead(404, {
        'Content-Type': 'application/json'
      });
      return res.end("Not a good path!");
    }
  }).listen(2222, '127.0.0.1');

}).call(this);
