// Generated by CoffeeScript 1.10.0
(function() {
  var http, metrics, users;

  http = require('http');

  users = require('../lib/users.js');

  metrics = require('../lib/metrics.js');

  http.createServer(function(req, res) {
    var metric, password, path, response;
    path = req.url.split("/").splice(1, 2);
    if (path[0] === 'get') {
      metric = users.login(path[1], "merignac33");
      response = {
        info: "here's your metric!",
        metric: metric
      };
      res.writeHead(200, {
        'Content-Type': 'application/json'
      });
      return res.end(JSON.stringify(response));
    } else if (path[0] === 'save') {
      password = "merignac33";
      metric = [
        {
          value: 1337,
          timestamp: Date.now()
        }
      ];
      return users.save(path[1], password, function(id) {
        response = {
          info: "metric saved!",
          id: id
        };
        res.writeHead(200, {
          'Content-Type': 'application/json'
        });
        return res.end(JSON.stringify(response));
      });
    } else {
      res.writeHead(404, {
        'Content-Type': 'application/json'
      });
      return res.end("Not a good path!");
    }
  }).listen(2222, '127.0.0.1');

}).call(this);
