// Generated by CoffeeScript 1.10.0
(function() {
  var should, users;

  users = require('./users.js');

  should = require('should');

  describe('get() function', function() {
    return it('gets the user from a given ID', function() {
      var result;
      return result = users.get(0, function(result) {
        return result.id.should.equal(0);
      });
    });
  });

  describe('save() function', function() {
    return it('saves an user given its name', function() {
      var result;
      return result = users.save('debesson-le', function(result) {
        return result.name.should.equal('debesson-le');
      });
    });
  });

}).call(this);
