// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user");

  module.exports = {
    save: function(name, callback) {
      var rs, user;
      user = {};
      rs = db.createReadStream;
      return callback(user);
    },
    get: function(id, callback) {
      var user;
      user = {
        name: "debesson",
        id: id
      };
      return callback(user);
    }
  };

}).call(this);
