// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user");

  module.exports = {
    save: function(name, password, callback) {
      var user, ws;
      user = {};
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "user:" + name,
        value: "" + password
      });
      return ws.end();
    },
    get: function(name, callback) {
      var rs, user;
      user = {};
      rs = db.createReadStream({
        gte: "user:" + name,
        lte: "user:" + name
      });
      rs.on('data', function(data) {
        return user = {
          name: name,
          password: data.value
        };
      });
      rs.on('error', function() {
        return callback("Error");
      });
      return rs.on('close', function() {
        return callback(user);
      });
    },
    login: function(name, password) {
      var user;
      user = {};
      return this.get(name, function(user) {
        if (password === user.password) {
          return true;
        }
        return false;
      });
    }
  };

}).call(this);
