// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user");

  module.exports = {
    save: function(name, password, callback) {
      var user, ws;
      user = {};
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "user:" + name,
        value: "" + password
      });
      return ws.end();
    },
    get: function(name, callback) {
      var rs;
      rs = db.createReadStream({
        gte: "metric:" + name,
        lte: "metric:" + name
      });
      rs.on('data', function(data) {
        return data.value;
      });
      rs.on('error', function() {
        return callback("Error");
      });
      return rs.on('close', function() {
        return callback("Error");
      });
    },
    login: function(name, password, callback) {
      if (password === this.get(name)) {
        true;
      }
      return false;
    }
  };

}).call(this);
